apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hive-beta.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hive-beta.name" . }}
    {{- include "hive-beta.labels" . | nindent 4 }}
data:
  hive-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
        <property>
            <name>javax.jdo.option.ConnectionURL</name>
            <value>jdbc:mysql://{{ .Values.mysql.endpoint }}:{{ .Values.mysql.port }}/{{ .Values.mysql.database }}</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>com.mysql.jdbc.Driver</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            <value>{{ .Values.mysql.username }}</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>{{ .Values.mysql.password }}</value>
        </property>
        <property>
            <name>hive.server2.enable.doAs</name>
            <value>false</value>
        </property>
        <property>
            <name>datanucleus.autoCreateSchema</name>
            <value>true</value>
        </property>
        {{- if not (index .Values.conf "hive_site" "hive_metastore_uris")  }}
        <property>
            <name>hive.metastore.uris</name>
            <value>thrift://{{ include "hive-beta.fullname" . }}:9083</value>
        </property>
      {{- end }}
      {{- if not (index .Values.conf "hive_site" "hive_metastore_warehouse_dir")  }}
        <property>
            <name>hive.metastore.warehouse.dir</name>
            <value>{{ .Values.conf.hive_site.hive_metastore_warehouse_dir }}</value>
        </property>
    {{- end }}
      {{- if index .Values.conf "hive_site" }}
      {{- range $key, $value := index .Values.conf "hive_site" }}
        <property><name>{{ $key }}</name><value>{{ $value }}</value></property>
      {{- end }}
      {{- end }}
    </configuration>

  hiveserver2-site.xml: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>
    <configuration>
        <property>
            <name>javax.jdo.option.ConnectionURL</name>
            <value>jdbc:mysql://{{ .Values.mysql.endpoint }}:{{ .Values.mysql.port }}/{{ .Values.mysql.database }}</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionDriverName</name>
            <value>com.mysql.jdbc.Driver</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionUserName</name>
            <value>{{ .Values.mysql.username }}</value>
        </property>
        <property>
            <name>javax.jdo.option.ConnectionPassword</name>
            <value>{{ .Values.mysql.password }}</value>
        </property>
        <property>
            <name>hive.server2.enable.doAs</name>
            <value>false</value>
        </property>
        <property>
            <name>datanucleus.autoCreateSchema</name>
            <value>true</value>
        </property>
        {{- if not (index .Values.conf "hive_site" "hive_metastore_uris")  }}
        <property>
            <name>hive.metastore.uris</name>
            <value>thrift://{{ include "hive-beta.fullname" . }}:9083</value>
        </property>
      {{- end }}
      {{- if not (index .Values.conf "hive_site" "hive_metastore_warehouse_dir")  }}
        <property>
            <name>hive.metastore.warehouse.dir</name>
            <value>{{ .Values.conf.hive_site.hive_metastore_warehouse_dir }}</value>
        </property>
    {{- end }}
      {{- if index .Values.conf "hive_site" }}
      {{- range $key, $value := index .Values.conf "hive_site" }}
        <property><name>{{ $key }}</name><value>{{ $value }}</value></property>
      {{- end }}
      {{- end }}
    </configuration>
