apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.name" . }}
  labels:
    {{- include "hive.labels" $ | trim | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - name: thrift
      port: 9083
      targetPort: 9083
      protocol: TCP
  selector:
    {{- include "hive.selectorLabels" . | nindent 4 }}