apiVersion: v1
kind: Service
metadata:
  name: {{ include "ranger.fullname" . }}-admin
  labels:
    app.kubernetes.io/name: {{ include "ranger.name" . }}
    helm.sh/chart: {{ include "ranger.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ include "ranger.fullname" . }}-admin
spec:
  type: {{ .Values.service.admin.type }}
  ports:
    - port: {{ .Values.service.admin.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ranger.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ include "ranger.fullname" . }}-admin
