image:
  repository: public.ecr.aws/y8d7x2g6/dep-public/emr
  tag: 1.0.0
  pullPolicy: IfNotPresent
#  pullPolicy: Always

# The version of the hadoop libraries being used in the image.
hadoopVersion: 3.3.2
logLevel: INFO

# Select antiAffinity as either hard or soft, default is soft
antiAffinity: "soft"

hdfs:
  nameNode:
    pdbMinAvailable: 1

    replicas: 3

    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

  dataNode:
    externalHostname: example.com
    externalDataPortRangeStart: 50500
    externalHTTPPortRangeStart: 51000

    replicas: 3

    pdbMinAvailable: 1

    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

  webhdfs:
    enabled: false

yarn:
  resourceManager:
    pdbMinAvailable: 1

    replicas: 3

    resources:
      requests:
        memory: "256Mi"
        cpu: "10m"
      limits:
        memory: "2048Mi"
        cpu: "2000m"

  nodeManager:
    pdbMinAvailable: 1

    # The number of YARN NodeManager instances.
    replicas: 3

    # Create statefulsets in parallel (K8S 1.7+)
    parallelCreate: false

    # CPU and memory resources allocated to each node manager pod.
    # This should be tuned to fit your workload.
    resources:
      requests:
        memory: "2048Mi"
        cpu: "1000m"
      limits:
        memory: "2048Mi"
        cpu: "1000m"

hive:
  mysql:
    endpoint: mysql
    database: hive
    port: 3306
    username: root
    password: root
  warehouse:
    location: hdfs:///hive
  resources:
    requests:
      memory: "256Mi"
      cpu: "10m"
    limits:
      memory: "2048Mi"
      cpu: "2000m"

persistence:
  nameNode:
    enabled: true
    storageClass: ebs-sc-hadoop
    accessMode: ReadWriteOnce
    size: 50Gi

  dataNode:
    enabled: true
    storageClass: ebs-sc-hadoop
    accessMode: ReadWriteOnce
    size: 50Gi

ldap:
  url: ldap://localhost:1389
  bind_dn: cn=admin,dc=example,dc=org
  bind_password: admin
  base_dn: ou=People,dc=example,dc=org