{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
 {{- include "hive.labels" $ | trim | nindent 4 }}
  name: {{ include "hive.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "hive.name" . }}
roleRef:
  kind: Role
  name:  {{ include "hive.name" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}