{{- if and .Values.rbac.create .Values.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
 {{- include "hive.labels" $ | trim | nindent 4 }}
  name: {{ include "hive.name" . }}
{{- if .Values.rbac.serviceAccount.annotations }}
  annotations: {{- toYaml .Values.rbac.serviceAccount.annotations | trim | nindent 4 }}
{{- end }}
automountServiceAccountToken: {{ .Values.rbac.serviceAccount.automountServiceAccountToken }}
{{- end }}