# Default values for hive-beta.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: 837282828706.dkr.ecr.ap-northeast-1.amazonaws.com/big-data-platform/beta/hive
  tag: latest
  pullPolicy: IfNotPresent

mysql:
  endpoint: mysql
  database: hive
  port: 3306
  username: root
  password: root

#  initdbScriptsConfigMap: hive-metastore-mysql-init

conf:
  hive_site:
    hive_metastore_warehouse_dir: ""
  core_site:
    hdfs_endpoint: ""

resources:
  requests:
    memory: "256Mi"
    cpu: "10m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"

persistence:
  enabled: true
  storageClass: ebs-sc
  accessMode: ReadWriteOnce
  size: 8Gi