image:
  repository: 837282828706.dkr.ecr.ap-northeast-1.amazonaws.com/big-data-platform/beta/hadoop
  tag: latest
  pullPolicy: IfNotPresent

# The version of the hadoop libraries being used in the image.
hadoopVersion: 3.3.2
logLevel: INFO

# Select antiAffinity as either hard or soft, default is soft
antiAffinity: "soft"

hdfs:
  nameNode:
    pdbMinAvailable: 1

    resources:
      requests:
        memory: 256m
        cpu: 10m
      limits:
        memory: 2048m
        cpu: 1000m

  dataNode:
    # Will be used as dfs.datanode.hostname
    # You still need to set up services + ingress for every DN
    # Datanodes will expect to
    externalHostname: example.com
    externalDataPortRangeStart: 50500
    externalHTTPPortRangeStart: 51000

    replicas: 1

    pdbMinAvailable: 1

    resources:
      requests:
        cpu: 10m
        memory: 256Mi
      limits:
        cpu: 1000m
        memory: 2048Mi

  webhdfs:
    enabled: false

yarn:
  resourceManager:
    pdbMinAvailable: 1

    resources:
      requests:
        memory: 256m
        cpu: 10m
      limits:
        memory: 2048m
        cpu: 1000m

  nodeManager:
    pdbMinAvailable: 1

    # The number of YARN NodeManager instances.
    replicas: 1

    # Create statefulsets in parallel (K8S 1.7+)
    parallelCreate: false

    # CPU and memory resources allocated to each node manager pod.
    # This should be tuned to fit your workload.
    resources:
      requests:
        memory: 2048m
        cpu: 1000m
      limits:
        memory: 2048m
        cpu: 1000m

persistence:
  nameNode:
    enabled: false
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 50Gi

  dataNode:
    enabled: false
    storageClass: "-"
    accessMode: ReadWriteOnce
    size: 200Gi