{{ if .Values.domain_database }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "trino.coordinator" . }}-db-init
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: coordinator
    {{- if .Values.commonLabels }}
    {{- tpl (toYaml .Values.commonLabels) . | nindent 4 }}
    {{- end }}
data:
  db-init.sql:
    CREATE DATABASE IF NOT EXISTS {{ .Values.domain_database }};
    CREATE DATABASE IF NOT EXISTS ppe_{{ .Values.domain_database }};
{{ end }}