apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "openldap.fullname" . }}-postinstall
  labels:
    app: {{ template "openldap.name" . }}
    chart: {{ template "openldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
data:
  ldap_initialization.sh: |-
{{ .Files.Get "scripts/ldap_initialization.sh" | indent 4}}