apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "openldap.fullname" . }}-postinstall-job
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "openldap.fullname" . }}-postinstall-job
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: {{ .Chart.Name }}-postinstall-job
        image: {{ include "openldap.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c", "/opt/scripts/ldap_initialization.sh" ]
        env:
          - name: USER_PASSWORD
            value: test
          - name: USER_CN
            value: test
          - name: DOMAIN
            value: {{ .Values.global.ldapDomain }}
          - name: ADMIN_DN
            value: cn={{ .Values.global.adminUser }},{{ .Values.global.ldapDomain }}
          - name: ADMIN_PASSWORD
            value: {{ .Values.global.adminPassword }}
        volumeMounts:
          - name: config-volume
            mountPath: /opt/scripts
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "openldap.fullname" . }}-fs-postinstall
            defaultMode: 0777