apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}"-post-install-job
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-post-install-job
          image: {{ include "openldap.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [
            "sh",
            "-c",
            "export test_password=$(slappasswd -s 'test')",
            "cat <<EOF > /tmp/add_test_user.ldif
             dn: cn=test,ou=People,{{ .Values.global.ldapDomain }}
             objectClass: inetOrgPerson
             uid: test
             sn: test
             cn: test
             displayName: Ben
             employeeType: LDAP_ADMIN
             userPassword: $test_password
             EOF",
            "ldapadd -c -x -W {{ .Values.global.adminPassword }} -D 'cn={{ .Values.global.adminUser }},{{ .Values.global.ldapDomain }}' -b '{{ .Values.global.ldapDomain }}' -f /tmp/add_test_user.ldif"
          ]